name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: Avkroken/.github/.github/workflows/release-please.yml@dbf52a4014fb0a2fc011eed924d5f2a1cfcaabaa
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
